const { ESTATUS_CANON } = require('./normalize');

const PERSONA_COLS = [
  { header: 'Cédula', key: 'ci', type: 'text', required: true, width: 14 },
  { header: 'Nombre', key: 'nombre', type: 'text', required: true, width: 18 },
  { header: 'Apellido', key: 'apellido', type: 'text', width: 18 },
  { header: 'Teléfono', key: 'telefono', type: 'text', width: 16 },
  { header: 'Correo', key: 'email', type: 'text', width: 24 },
  { header: 'Fecha de nacimiento', key: 'fecha_nacimiento', type: 'date', width: 18 },
  { header: 'Residencia', key: 'residencia', type: 'text', width: 20 },
];

const ESTATUS_VOLUNTARIO = ['Activo', 'Inactivo'];
const ESTATUS_ESTUDIANTE = ESTATUS_CANON.filter((e) => e !== 'Activo' && e !== 'Inactivo');

function col(header, key, type, opts = {}) {
  return {
    header,
    key,
    type,
    required: opts.required || false,
    width: opts.width || 16,
    options: opts.options,
  };
}

const SCHEMAS = {
  voluntarios: {
    moduleName: 'Voluntarios',
    fileName: 'plantilla_voluntarios.xlsx',
    table: 'voluntarios',
    idColumn: 'voluntario_id',
    entidad: 'voluntario',
    insertColumns: [
      'fecha_inicio',
      'fecha_retiro',
      'estatus',
      'profesion_oficio',
      'lugar_trabajo',
      'asistencias',
      'actividad',
    ],
    personaFields: ['ci', 'nombre', 'apellido', 'telefono', 'email', 'fecha_nacimiento', 'residencia', 'fecha_induccion'],
    columns: [
      ...PERSONA_COLS,
      col('Fecha de inducción', 'fecha_induccion', 'date', { width: 18 }),
      col('Fecha de inicio', 'fecha_inicio', 'date', { width: 18 }),
      col('Fecha de retiro', 'fecha_retiro', 'date', { width: 18 }),
      col('Estatus', 'estatus', 'text', { options: ESTATUS_VOLUNTARIO, width: 14 }),
      col('Profesión u oficio', 'profesion_oficio', 'text', { width: 22 }),
      col('Lugar de trabajo', 'lugar_trabajo', 'text', { width: 24 }),
      col('Actividad', 'actividad', 'text', { width: 18 }),
      col('Asistencias', 'asistencias', 'int', { width: 12 }),
    ],
    estatusOptions: ESTATUS_VOLUNTARIO,
    isVolunteer: true,
    matchColumns: [],
  },

  labor_social: {
    moduleName: 'Labor Social',
    fileName: 'plantilla_labor_social.xlsx',
    table: 'labor_social',
    idColumn: 'labor_social_id',
    entidad: 'labor_social',
    insertColumns: [
      'colegio',
      'nivel',
      'carrera',
      'expediente',
      'anio',
      'estatus',
      'fecha_inicio',
      'fecha_culminacion',
      'representante',
      'telefono_representante',
      'email_representante',
      'actividad_apoyo',
      'fecha_carta_culminacion',
    ],
    personaFields: [
      'ci',
      'nombre',
      'apellido',
      'telefono',
      'email',
      'residencia',
      'fecha_induccion',
    ],
    columns: [
      col('Cédula', 'ci', 'text', { required: true, width: 14 }),
      col('Nombre', 'nombre', 'text', { required: true, width: 18 }),
      col('Apellido', 'apellido', 'text', { width: 18 }),
      col('Teléfono', 'telefono', 'text', { width: 16 }),
      col('Email', 'email', 'text', { width: 24 }),
      col('Residencia', 'residencia', 'text', { width: 20 }),
      col('Fecha de Inducción', 'fecha_induccion', 'date', { width: 18 }),
      col('Colegio', 'colegio', 'text', { width: 22 }),
      col('Nivel', 'nivel', 'text', { width: 14 }),
      col('Año', 'anio', 'int', { width: 10 }),
      col('Estatus', 'estatus', 'text', { options: ESTATUS_ESTUDIANTE, width: 14 }),
      col('Inicio', 'fecha_inicio', 'date', { width: 18 }),
      col('Culminación', 'fecha_culminacion', 'date', { width: 20 }),
      col('Representante', 'representante', 'text', { width: 20 }),
      col('Teléfono2', 'telefono_representante', 'text', { width: 18 }),
      col('Email representante', 'email_representante', 'text', { width: 24 }),
      col('Actividad de apoyo', 'actividad_apoyo', 'text', { width: 24 }),
      col('Carta Culminación digital', 'fecha_carta_culminacion', 'date', { width: 22 }),
      col('Observaciones', 'observaciones', 'text', { width: 36 }),
    ],
    estatusOptions: ESTATUS_ESTUDIANTE,
    matchColumns: [],
    keepLatest: true,
  },

  servicio_comunitario: {
    moduleName: 'Servicio Comunitario',
    fileName: 'plantilla_servicio_comunitario.xlsx',
    table: 'servicio_comunitario_universitario',
    idColumn: 'servicio_comunitario_id',
    entidad: 'servicio_comunitario',
    insertColumns: [
      'instituto',
      'carrera',
      'proyecto',
      'anio',
      'estatus',
      'fecha_inicio',
      'fecha_culminacion',
    ],
    personaFields: ['ci', 'nombre', 'apellido', 'telefono', 'email', 'fecha_nacimiento', 'residencia'],
    columns: [
      ...PERSONA_COLS,
      col('Instituto', 'instituto', 'text', { width: 22 }),
      col('Carrera', 'carrera', 'text', { width: 20 }),
      col('Proyecto', 'proyecto', 'text', { width: 24 }),
      col('Año', 'anio', 'int', { width: 10 }),
      col('Estatus', 'estatus', 'text', { options: ESTATUS_ESTUDIANTE, width: 14 }),
      col('Fecha de inicio', 'fecha_inicio', 'date', { width: 18 }),
      col('Fecha de culminación', 'fecha_culminacion', 'date', { width: 20 }),
    ],
    estatusOptions: ESTATUS_ESTUDIANTE,
    matchColumns: ['anio', 'fecha_inicio'],
  },

  pasantia: {
    moduleName: 'Pasantías',
    fileName: 'plantilla_pasantias.xlsx',
    table: 'pasantia_tesis_proyecto',
    idColumn: 'pasantia_tesis_proyecto_id',
    entidad: 'pasantia',
    insertColumns: [
      'tipo',
      'carrera',
      'instituto',
      'tutor_academico',
      'tutor_institucional',
      'anio',
      'estatus',
      'fecha_inicio',
      'fecha_culminacion',
    ],
    personaFields: ['ci', 'nombre', 'apellido', 'telefono', 'email', 'fecha_nacimiento', 'residencia'],
    columns: [
      ...PERSONA_COLS,
      col('Tipo', 'tipo', 'text', { width: 16 }),
      col('Carrera', 'carrera', 'text', { width: 20 }),
      col('Instituto', 'instituto', 'text', { width: 22 }),
      col('Tutor académico', 'tutor_academico', 'text', { width: 20 }),
      col('Tutor institucional', 'tutor_institucional', 'text', { width: 22 }),
      col('Año', 'anio', 'int', { width: 10 }),
      col('Estatus', 'estatus', 'text', { options: ESTATUS_ESTUDIANTE, width: 14 }),
      col('Fecha de inicio', 'fecha_inicio', 'date', { width: 18 }),
      col('Fecha de culminación', 'fecha_culminacion', 'date', { width: 20 }),
    ],
    estatusOptions: ESTATUS_ESTUDIANTE,
    matchColumns: ['anio', 'fecha_inicio'],
  },

  otros: {
    moduleName: 'Otros',
    fileName: 'plantilla_otros.xlsx',
    table: 'otros',
    idColumn: 'otros_id',
    entidad: 'otros',
    insertColumns: [
      'tipo_actividad',
      'institucion',
      'carrera',
      'anio',
      'estatus',
      'fecha_inicio',
      'fecha_culminacion',
    ],
    personaFields: ['ci', 'nombre', 'apellido', 'telefono', 'email', 'fecha_nacimiento', 'residencia'],
    columns: [
      ...PERSONA_COLS,
      col('Tipo de actividad', 'tipo_actividad', 'text', { width: 20 }),
      col('Institución', 'institucion', 'text', { width: 22 }),
      col('Carrera', 'carrera', 'text', { width: 20 }),
      col('Año', 'anio', 'int', { width: 10 }),
      col('Estatus', 'estatus', 'text', { options: ESTATUS_ESTUDIANTE, width: 14 }),
      col('Fecha de inicio', 'fecha_inicio', 'date', { width: 18 }),
      col('Fecha de culminación', 'fecha_culminacion', 'date', { width: 20 }),
    ],
    estatusOptions: ESTATUS_ESTUDIANTE,
    matchColumns: ['anio', 'fecha_inicio', 'tipo_actividad'],
  },
};

function getSchemaByKey(key) {
  return SCHEMAS[key] || null;
}

module.exports = {
  SCHEMAS,
  getSchemaByKey,
  PERSONA_COLS,
  ESTATUS_VOLUNTARIO,
  ESTATUS_ESTUDIANTE,
};
